import { config } from "@workspace/eslint-config/base"

/** @type {import("eslint").Linter.Config} */
export default [
  ...config,
  // Generated by `pnpm --filter studio type`; never hand-edited.
  { ignores: ["src/sanity.types.ts"] },
]
