/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type PersonReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "person"
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type TagReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "tag"
}

export type JournalEntry = {
  _id: string
  _type: "journalEntry"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  author?: PersonReference
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  tags?: Array<
    {
      _key: string
    } & TagReference
  >
  body?: BlockContent
  publishedAt?: string
  featured?: boolean
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote"
      listItem?: "bullet"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: "image"
      _key: string
    }
>

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type Post = {
  _id: string
  _type: "post"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  author?: PersonReference
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  tags?: Array<
    {
      _key: string
    } & TagReference
  >
  body?: BlockContent
  publishedAt?: string
  featured?: boolean
}

export type Tag = {
  _id: string
  _type: "tag"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  description?: string
}

export type Testimonial = {
  _id: string
  _type: "testimonial"
  _createdAt: string
  _updatedAt: string
  _rev: string
  quote?: string
  author?: PersonReference
  context?: string
  featured?: boolean
  givenAt?: string
  orderRank?: string
}

export type OrganizationReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "organization"
}

export type Person = {
  _id: string
  _type: "person"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  photo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  position?: string
  organization?: OrganizationReference
  organizationName?: string
  website?: string
  socials?: Array<{
    platform?: "linkedin" | "twitter" | "instagram" | "youtube" | "github"
    url?: string
    _key: string
  }>
  orderRank?: string
}

export type ExperienceReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "experience"
}

export type SkillReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "skill"
}

export type Project = {
  _id: string
  _type: "project"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  kind?: "professional" | "freelance" | "personal" | "open-source" | "research"
  status?: "live" | "in-development" | "unlaunched" | "archived"
  tagline?: string
  summary?: string
  body?: BlockContent
  icon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  gallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: "image"
    _key: string
  }>
  organization?: OrganizationReference
  relatedExperience?: ExperienceReference
  skills?: Array<
    {
      _key: string
    } & SkillReference
  >
  links?: Array<{
    label?: string
    url?: string
    type?:
      | "live-site"
      | "repo"
      | "play-store"
      | "app-store"
      | "case-study"
      | "video"
      | "paper"
    _key: string
  }>
  githubRepo?: string
  startDate?: string
  completedAt?: string
  featured?: boolean
  archived?: boolean
  orderRank?: string
}

export type Publication = {
  _id: string
  _type: "publication"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  venue?: string
  publishedAt?: string
  abstract?: string
  authors?: Array<string>
  doi?: string
  url?: string
  orderRank?: string
}

export type Certification = {
  _id: string
  _type: "certification"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  organization?: OrganizationReference
  issuedAt?: string
  credentialId?: string
  verifyUrl?: string
  archived?: boolean
  orderRank?: string
}

export type Experience = {
  _id: string
  _type: "experience"
  _createdAt: string
  _updatedAt: string
  _rev: string
  role?: string
  organization?: OrganizationReference
  kind?: "work" | "community" | "education"
  employmentType?:
    | "full-time"
    | "part-time"
    | "internship"
    | "contract"
    | "freelance"
    | "volunteer"
  workMode?: "on-site" | "remote" | "hybrid"
  location?: string
  startDate?: string
  endDate?: string
  isCurrent?: boolean
  summary?: string
  highlights?: Array<string>
  skills?: Array<
    {
      _key: string
    } & SkillReference
  >
  credential?: string
  links?: Array<{
    label?: string
    url?: string
    type?:
      "live-site" | "repo" | "certificate" | "letter" | "patent" | "publication"
    _key: string
  }>
  featured?: boolean
  orderRank?: string
}

export type Organization = {
  _id: string
  _type: "organization"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  website?: string
  description?: string
  orderRank?: string
}

export type Value = {
  _id: string
  _type: "value"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  illustration?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  orderRank?: string
}

export type Service = {
  _id: string
  _type: "service"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  description?: string
  icon?:
    | "Code2"
    | "Database"
    | "Search"
    | "Cloud"
    | "Wrench"
    | "Rocket"
    | "Server"
    | "FileCode"
    | "Globe"
    | "Sparkles"
    | "Layers"
    | "Terminal"
  illustration?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  orderRank?: string
}

export type Skill = {
  _id: string
  _type: "skill"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  icon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  category?:
    | "languages"
    | "frontend-mobile"
    | "backend"
    | "testing"
    | "payments-security"
    | "cms"
    | "cloud-infrastructure"
    | "auth-security"
    | "ai-ml"
    | "messaging-integrations"
    | "devops-tooling"
    | "databases"
    | "collaboration"
    | "other"
  featured?: boolean
  orderRank?: string
}

export type Faqs = {
  _id: string
  _type: "faqs"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  faqItems?: Array<{
    question?: string
    answer?: string
    _key: string
  }>
}

export type Legal = {
  _id: string
  _type: "legal"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  content?: BlockContent
}

export type SanityFileAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset"
}

export type LegalReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "legal"
}

export type SiteConfig = {
  _id: string
  _type: "siteConfig"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  footerBlurb?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  twitterImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  heroName?: string
  heroRoles?: Array<string>
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  aboutHeadingLead?: string
  aboutHeadingHighlight?: string
  aboutBody?: string
  aboutHighlights?: Array<{
    title?: string
    description?: string
    _key: string
  }>
  aboutImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  aboutPageHeadingLead?: string
  aboutPageHeadingHighlight?: string
  aboutPageIntro?: string
  aboutPageStoryHeadingLead?: string
  aboutPageStoryHeadingHighlight?: string
  aboutPageStoryHeadingTrail?: string
  aboutPageStory?: Array<string>
  aboutPageValuesHeading?: string
  aboutPageValuesIntro?: string
  aboutPagePortrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  testimonialsHeadingLead?: string
  testimonialsHeadingHighlight?: string
  testimonialsIntro?: string
  phoneNumbers?: Array<{
    number?: string
    label?: string
    _key: string
  }>
  emails?: Array<{
    email?: string
    label?: string
    _key: string
  }>
  contactNotificationEmail?: string
  address?: {
    street?: string
    city?: string
    state?: string
    postalCode?: string
    country?: string
  }
  socialMedia?: Array<{
    platform?:
      | "github"
      | "linkedin"
      | "twitter"
      | "instagram"
      | "youtube"
      | "blog"
      | "facebook"
      | "whatsapp"
      | "discord"
      | "telegram"
    url?: string
    label?: string
    _key: string
  }>
  resumePdf?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: "file"
  }
  footerLegalLinks?: Array<
    {
      _key: string
    } & LegalReference
  >
  rickrollAudio?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: "file"
  }
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | PersonReference
  | SanityImageAssetReference
  | TagReference
  | JournalEntry
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Post
  | Tag
  | Testimonial
  | OrganizationReference
  | Person
  | ExperienceReference
  | SkillReference
  | Project
  | Publication
  | Certification
  | Experience
  | Organization
  | Value
  | Service
  | Skill
  | Faqs
  | Legal
  | SanityFileAssetReference
  | LegalReference
  | SiteConfig
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../../packages/sanity/src/query.ts
// Variable: SITE_CONFIG_QUERY
// Query: *[_type == "siteConfig"][0] {    _id,    title,    description,    footerBlurb,    ogImage {      asset->,      hotspot,      crop,      alt    },    twitterImage {      asset->,      hotspot,      crop,      alt    },    logo {      asset->,      hotspot,      crop,      alt    },    heroName,    heroRoles,    heroImage {      asset->,      hotspot,      crop,      alt    },    aboutHeadingLead,    aboutHeadingHighlight,    aboutBody,    aboutHighlights[] {      title,      description    },    aboutImage {      asset->,      hotspot,      crop,      alt    },    testimonialsHeadingLead,    testimonialsHeadingHighlight,    testimonialsIntro,    phoneNumbers[] {      number,      label    },    emails[] {      email,      label    },    contactNotificationEmail,    address {      street,      city,      state,      postalCode,      country    },    socialMedia[] {      platform,      url,      label    },    resumePdf {      asset->    },    rickrollAudio {      asset->    }  }
export type SITE_CONFIG_QUERY_RESULT = {
  _id: string
  title: string | null
  description: string | null
  footerBlurb: string | null
  ogImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  twitterImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  logo: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  heroName: string | null
  heroRoles: Array<string> | null
  heroImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  aboutHeadingLead: string | null
  aboutHeadingHighlight: string | null
  aboutBody: string | null
  aboutHighlights: Array<{
    title: string | null
    description: string | null
  }> | null
  aboutImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  testimonialsHeadingLead: string | null
  testimonialsHeadingHighlight: string | null
  testimonialsIntro: string | null
  phoneNumbers: Array<{
    number: string | null
    label: string | null
  }> | null
  emails: Array<{
    email: string | null
    label: string | null
  }> | null
  contactNotificationEmail: string | null
  address: {
    street: string | null
    city: string | null
    state: string | null
    postalCode: string | null
    country: string | null
  } | null
  socialMedia: Array<{
    platform:
      | "blog"
      | "discord"
      | "facebook"
      | "github"
      | "instagram"
      | "linkedin"
      | "telegram"
      | "twitter"
      | "whatsapp"
      | "youtube"
      | null
    url: string | null
    label: string | null
  }> | null
  resumePdf: {
    asset: {
      _id: string
      _type: "sanity.fileAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      source?: SanityAssetSourceData
    } | null
  } | null
  rickrollAudio: {
    asset: {
      _id: string
      _type: "sanity.fileAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      source?: SanityAssetSourceData
    } | null
  } | null
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "siteConfig"][0] {    aboutPageHeadingLead,    aboutPageHeadingHighlight,    aboutPageIntro,    aboutPageStoryHeadingLead,    aboutPageStoryHeadingHighlight,    aboutPageStoryHeadingTrail,    aboutPageStory,    aboutPageValuesHeading,    aboutPageValuesIntro,    aboutPagePortrait {      asset->,      hotspot,      crop,      alt    }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  aboutPageHeadingLead: string | null
  aboutPageHeadingHighlight: string | null
  aboutPageIntro: string | null
  aboutPageStoryHeadingLead: string | null
  aboutPageStoryHeadingHighlight: string | null
  aboutPageStoryHeadingTrail: string | null
  aboutPageStory: Array<string> | null
  aboutPageValuesHeading: string | null
  aboutPageValuesIntro: string | null
  aboutPagePortrait: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: FOOTER_LEGAL_LINKS_QUERY
// Query: *[_type == "siteConfig"][0].footerLegalLinks[]-> {    _id,    title,    slug,    description,    _updatedAt  }
export type FOOTER_LEGAL_LINKS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  _updatedAt: string
}> | null

// Source: ../../packages/sanity/src/query.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faqs"][0] {    ...,    faqItems[]{ ... }  }
export type FAQS_QUERY_RESULT = {
  _id: string
  _type: "faqs"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  faqItems: Array<{
    question?: string
    answer?: string
    _key: string
  }> | null
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: LEGAL_DOCUMENTS_QUERY
// Query: *[_type == "legal"] | order(_updatedAt desc) {    _id,    title,    slug,    description,    _createdAt,    _updatedAt  }
export type LEGAL_DOCUMENTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  _createdAt: string
  _updatedAt: string
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: LEGAL_DOCUMENT_BY_SLUG_QUERY
// Query: *[_type == "legal" && slug.current == $slug][0] {    _id,    title,    slug,    description,    content,    _createdAt,    _updatedAt  }
export type LEGAL_DOCUMENT_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  content: BlockContent | null
  _createdAt: string
  _updatedAt: string
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: FEATURED_SKILLS_QUERY
// Query: *[_type == "skill" && featured == true] | order(orderRank asc, name asc) {    _id,    name,    icon {      asset->,      hotspot,      crop,      alt    },    category  }
export type FEATURED_SKILLS_QUERY_RESULT = Array<{
  _id: string
  name: string | null
  icon: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  category:
    | "ai-ml"
    | "auth-security"
    | "backend"
    | "cloud-infrastructure"
    | "cms"
    | "collaboration"
    | "databases"
    | "devops-tooling"
    | "frontend-mobile"
    | "languages"
    | "messaging-integrations"
    | "other"
    | "payments-security"
    | "testing"
    | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: SKILLS_QUERY
// Query: *[_type == "skill"] | order(category asc, orderRank asc, name asc) {    _id,    name,    icon {      asset->,      hotspot,      crop,      alt    },    category  }
export type SKILLS_QUERY_RESULT = Array<{
  _id: string
  name: string | null
  icon: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  category:
    | "ai-ml"
    | "auth-security"
    | "backend"
    | "cloud-infrastructure"
    | "cms"
    | "collaboration"
    | "databases"
    | "devops-tooling"
    | "frontend-mobile"
    | "languages"
    | "messaging-integrations"
    | "other"
    | "payments-security"
    | "testing"
    | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(orderRank asc) {    _id,    name,    description,    icon,    illustration {      asset->,      hotspot,      crop,      alt    }  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string
  name: string | null
  description: string | null
  icon:
    | "Cloud"
    | "Code2"
    | "Database"
    | "FileCode"
    | "Globe"
    | "Layers"
    | "Rocket"
    | "Search"
    | "Server"
    | "Sparkles"
    | "Terminal"
    | "Wrench"
    | null
  illustration: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: SERVICES_BY_IDS_QUERY
// Query: *[_type == "service" && _id in $ids] {    _id,    name  }
export type SERVICES_BY_IDS_QUERY_RESULT = Array<{
  _id: string
  name: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: VALUES_QUERY
// Query: *[_type == "value"] | order(orderRank asc) {    _id,    title,    description,    illustration {      asset->,      hotspot,      crop,      alt    }  }
export type VALUES_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  description: string | null
  illustration: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: FEATURED_EXPERIENCES_QUERY
// Query: *[_type == "experience" && kind == "work" && featured == true] | order(orderRank asc) {    _id,    role,    organization-> {      _id,      name,      website,      logo {        asset->,        hotspot,        crop,        alt      }    },    employmentType,    startDate,    endDate,    isCurrent,    summary  }
export type FEATURED_EXPERIENCES_QUERY_RESULT = Array<{
  _id: string
  role: string | null
  organization: {
    _id: string
    name: string | null
    website: string | null
    logo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
  } | null
  employmentType:
    | "contract"
    | "freelance"
    | "full-time"
    | "internship"
    | "part-time"
    | "volunteer"
    | null
  startDate: string | null
  endDate: string | null
  isCurrent: boolean | null
  summary: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: EXPERIENCES_QUERY
// Query: *[_type == "experience" && kind in ["work", "community"]] | order(orderRank asc) {    _id,    role,    kind,    organization-> {      _id,      name,      website,      description,      logo {        asset->,        hotspot,        crop,        alt      }    },    employmentType,    workMode,    location,    startDate,    endDate,    isCurrent,    summary,    highlights,    skills[]-> {      _id,      name    },    links[] {      label,      url,      type    }  }
export type EXPERIENCES_QUERY_RESULT = Array<{
  _id: string
  role: string | null
  kind: "community" | "education" | "work" | null
  organization: {
    _id: string
    name: string | null
    website: string | null
    description: string | null
    logo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
  } | null
  employmentType:
    | "contract"
    | "freelance"
    | "full-time"
    | "internship"
    | "part-time"
    | "volunteer"
    | null
  workMode: "hybrid" | "on-site" | "remote" | null
  location: string | null
  startDate: string | null
  endDate: string | null
  isCurrent: boolean | null
  summary: string | null
  highlights: Array<string> | null
  skills: Array<{
    _id: string
    name: string | null
  }> | null
  links: Array<{
    label: string | null
    url: string | null
    type:
      | "certificate"
      | "letter"
      | "live-site"
      | "patent"
      | "publication"
      | "repo"
      | null
  }> | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: EDUCATION_QUERY
// Query: *[_type == "experience" && kind == "education"] | order(orderRank asc) {    _id,    role,    organization-> {      _id,      name,      website,      logo {        asset->,        hotspot,        crop,        alt      }    },    location,    startDate,    endDate,    isCurrent,    summary,    highlights,    credential,    links[] {      label,      url,      type    }  }
export type EDUCATION_QUERY_RESULT = Array<{
  _id: string
  role: string | null
  organization: {
    _id: string
    name: string | null
    website: string | null
    logo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
  } | null
  location: string | null
  startDate: string | null
  endDate: string | null
  isCurrent: boolean | null
  summary: string | null
  highlights: Array<string> | null
  credential: string | null
  links: Array<{
    label: string | null
    url: string | null
    type:
      | "certificate"
      | "letter"
      | "live-site"
      | "patent"
      | "publication"
      | "repo"
      | null
  }> | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: CERTIFICATIONS_QUERY
// Query: *[_type == "certification" && archived != true] | order(orderRank asc) {    _id,    title,    organization-> {      _id,      name,      website,      logo {        asset->,        hotspot,        crop,        alt      }    },    issuedAt,    credentialId,    verifyUrl  }
export type CERTIFICATIONS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  organization: {
    _id: string
    name: string | null
    website: string | null
    logo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
  } | null
  issuedAt: string | null
  credentialId: string | null
  verifyUrl: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: ARCHIVED_CERTIFICATIONS_QUERY
// Query: *[_type == "certification" && archived == true] | order(orderRank asc) {    _id,    title,    organization-> {      _id,      name,      website,      logo {        asset->,        hotspot,        crop,        alt      }    },    issuedAt,    credentialId,    verifyUrl  }
export type ARCHIVED_CERTIFICATIONS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  organization: {
    _id: string
    name: string | null
    website: string | null
    logo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
  } | null
  issuedAt: string | null
  credentialId: string | null
  verifyUrl: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: PUBLICATIONS_QUERY
// Query: *[_type == "publication"] | order(orderRank asc) {    _id,    title,    venue,    publishedAt,    authors,    doi,    url,    abstract  }
export type PUBLICATIONS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  venue: string | null
  publishedAt: string | null
  authors: Array<string> | null
  doi: string | null
  url: string | null
  abstract: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true && archived != true] | order(orderRank asc) [0...6] {    _id,    title,    slug,    kind,    status,    tagline,    summary,    "hasBody": defined(body),    icon {      asset->,      hotspot,      crop,      alt    },    coverImage {      asset->,      hotspot,      crop,      alt    },    organization-> {      _id,      name,      website    },    skills[]-> {      _id,      name    },    links[] {      label,      url,      type    },    githubRepo,    startDate,    completedAt  }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  kind:
    | "freelance"
    | "open-source"
    | "personal"
    | "professional"
    | "research"
    | null
  status: "archived" | "in-development" | "live" | "unlaunched" | null
  tagline: string | null
  summary: string | null
  hasBody: false | true
  icon: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  organization: {
    _id: string
    name: string | null
    website: string | null
  } | null
  skills: Array<{
    _id: string
    name: string | null
  }> | null
  links: Array<{
    label: string | null
    url: string | null
    type:
      | "app-store"
      | "case-study"
      | "live-site"
      | "paper"
      | "play-store"
      | "repo"
      | "video"
      | null
  }> | null
  githubRepo: string | null
  startDate: string | null
  completedAt: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(orderRank asc) {    _id,    title,    slug,    kind,    status,    tagline,    summary,    "hasBody": defined(body),    archived,    featured,    icon {      asset->,      hotspot,      crop,      alt    },    coverImage {      asset->,      hotspot,      crop,      alt    },    organization-> {      _id,      name,      website    },    relatedExperience-> {      _id,      role,      employmentType    },    skills[]-> {      _id,      name    },    links[] {      label,      url,      type    },    githubRepo,    startDate,    completedAt  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  kind:
    | "freelance"
    | "open-source"
    | "personal"
    | "professional"
    | "research"
    | null
  status: "archived" | "in-development" | "live" | "unlaunched" | null
  tagline: string | null
  summary: string | null
  hasBody: false | true
  archived: boolean | null
  featured: boolean | null
  icon: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  organization: {
    _id: string
    name: string | null
    website: string | null
  } | null
  relatedExperience: {
    _id: string
    role: string | null
    employmentType:
      | "contract"
      | "freelance"
      | "full-time"
      | "internship"
      | "part-time"
      | "volunteer"
      | null
  } | null
  skills: Array<{
    _id: string
    name: string | null
  }> | null
  links: Array<{
    label: string | null
    url: string | null
    type:
      | "app-store"
      | "case-study"
      | "live-site"
      | "paper"
      | "play-store"
      | "repo"
      | "video"
      | null
  }> | null
  githubRepo: string | null
  startDate: string | null
  completedAt: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    slug,    kind,    status,    tagline,    summary,    body,    archived,    icon {      asset->,      hotspot,      crop,      alt    },    coverImage {      asset->,      hotspot,      crop,      alt    },    gallery[] {      asset->,      hotspot,      crop,      alt,      caption    },    organization-> {      _id,      name,      website,      description,      logo {        asset->,        hotspot,        crop,        alt      }    },    relatedExperience-> {      _id,      role,      employmentType,      startDate,      endDate,      isCurrent,      organization-> {        _id,        name      }    },    skills[]-> {      _id,      name,      category    },    links[] {      label,      url,      type    },    githubRepo,    startDate,    completedAt,    _updatedAt  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: Slug | null
  kind:
    | "freelance"
    | "open-source"
    | "personal"
    | "professional"
    | "research"
    | null
  status: "archived" | "in-development" | "live" | "unlaunched" | null
  tagline: string | null
  summary: string | null
  body: BlockContent | null
  archived: boolean | null
  icon: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  gallery: Array<{
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
    caption: string | null
  }> | null
  organization: {
    _id: string
    name: string | null
    website: string | null
    description: string | null
    logo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
  } | null
  relatedExperience: {
    _id: string
    role: string | null
    employmentType:
      | "contract"
      | "freelance"
      | "full-time"
      | "internship"
      | "part-time"
      | "volunteer"
      | null
    startDate: string | null
    endDate: string | null
    isCurrent: boolean | null
    organization: {
      _id: string
      name: string | null
    } | null
  } | null
  skills: Array<{
    _id: string
    name: string | null
    category:
      | "ai-ml"
      | "auth-security"
      | "backend"
      | "cloud-infrastructure"
      | "cms"
      | "collaboration"
      | "databases"
      | "devops-tooling"
      | "frontend-mobile"
      | "languages"
      | "messaging-integrations"
      | "other"
      | "payments-security"
      | "testing"
      | null
  }> | null
  links: Array<{
    label: string | null
    url: string | null
    type:
      | "app-store"
      | "case-study"
      | "live-site"
      | "paper"
      | "play-store"
      | "repo"
      | "video"
      | null
  }> | null
  githubRepo: string | null
  startDate: string | null
  completedAt: string | null
  _updatedAt: string
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(orderRank asc) {    _id,    title,    slug,    coverImage {      asset->,      hotspot,      crop,      alt    }  }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(orderRank asc) {      _id,  quote,  context,  givenAt,  author-> {    _id,    name,    position,    website,    organizationName,    photo {      asset->,      hotspot,      crop,      alt    },    organization-> {      _id,      name,      website,      logo {        asset->,        hotspot,        crop,        alt      }    }  }  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string
  quote: string | null
  context: string | null
  givenAt: string | null
  author: {
    _id: string
    name: string | null
    position: string | null
    website: string | null
    organizationName: string | null
    photo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
    organization: {
      _id: string
      name: string | null
      website: string | null
      logo: {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash?: string
          extension?: string
          mimeType?: string
          size?: number
          assetId?: string
          uploadId?: string
          path?: string
          url?: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
        alt: string | null
      } | null
    } | null
  } | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: FEATURED_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && featured == true] | order(orderRank asc) {      _id,  quote,  context,  givenAt,  author-> {    _id,    name,    position,    website,    organizationName,    photo {      asset->,      hotspot,      crop,      alt    },    organization-> {      _id,      name,      website,      logo {        asset->,        hotspot,        crop,        alt      }    }  }  }
export type FEATURED_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string
  quote: string | null
  context: string | null
  givenAt: string | null
  author: {
    _id: string
    name: string | null
    position: string | null
    website: string | null
    organizationName: string | null
    photo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
    organization: {
      _id: string
      name: string | null
      website: string | null
      logo: {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash?: string
          extension?: string
          mimeType?: string
          size?: number
          assetId?: string
          uploadId?: string
          path?: string
          url?: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
        alt: string | null
      } | null
    } | null
  } | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" &&   (!defined($tagSlug) || $tagSlug in tags[]->slug.current) &&  (!defined($search) || title match $search + "*" || excerpt match $search + "*")] | order(publishedAt desc) [$start...$end] {      _id,  title,  slug,  excerpt,  publishedAt,  "hasBody": defined(body),  coverImage {    asset->,    hotspot,    crop,    alt  },    author-> {    _id,    name,    photo {      asset->,      hotspot,      crop,      alt    },    website,    socials[] {      platform,      url    }  },  tags[]-> {    _id,    name,    slug  }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  excerpt: string | null
  publishedAt: string | null
  hasBody: false | true
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  author: {
    _id: string
    name: string | null
    photo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
    website: string | null
    socials: Array<{
      platform:
        "github" | "instagram" | "linkedin" | "twitter" | "youtube" | null
      url: string | null
    }> | null
  } | null
  tags: Array<{
    _id: string
    name: string | null
    slug: Slug | null
  }> | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: POST_COUNT_QUERY
// Query: count(*[_type == "post" &&   (!defined($tagSlug) || $tagSlug in tags[]->slug.current) &&  (!defined($search) || title match $search + "*" || excerpt match $search + "*")])
export type POST_COUNT_QUERY_RESULT = number

// Source: ../../packages/sanity/src/query.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {      _id,  title,  slug,  excerpt,  publishedAt,  body,  coverImage {    asset->,    hotspot,    crop,    alt  },  ogImage {    asset->,    hotspot,    crop,    alt  },    author-> {    _id,    name,    photo {      asset->,      hotspot,      crop,      alt    },    website,    socials[] {      platform,      url    }  },  tags[]-> {    _id,    name,    slug  },  _updatedAt  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: Slug | null
  excerpt: string | null
  publishedAt: string | null
  body: BlockContent | null
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  ogImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  author: {
    _id: string
    name: string | null
    photo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
    website: string | null
    socials: Array<{
      platform:
        "github" | "instagram" | "linkedin" | "twitter" | "youtube" | null
      url: string | null
    }> | null
  } | null
  tags: Array<{
    _id: string
    name: string | null
    slug: Slug | null
  }> | null
  _updatedAt: string
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {    _id,    title,    slug,    publishedAt  }
export type POST_SLUGS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  publishedAt: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: LATEST_POSTS_QUERY
// Query: *[_type == "post"] | order(publishedAt desc) [0...5] {    _id,    title,    slug,    publishedAt  }
export type LATEST_POSTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  publishedAt: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: JOURNAL_ENTRIES_QUERY
// Query: *[_type == "journalEntry" &&   (!defined($tagSlug) || $tagSlug in tags[]->slug.current) &&  (!defined($search) || title match $search + "*" || excerpt match $search + "*")] | order(publishedAt desc) [$start...$end] {      _id,  title,  slug,  excerpt,  publishedAt,  "hasBody": defined(body),  coverImage {    asset->,    hotspot,    crop,    alt  },    author-> {    _id,    name,    photo {      asset->,      hotspot,      crop,      alt    },    website,    socials[] {      platform,      url    }  },  tags[]-> {    _id,    name,    slug  }  }
export type JOURNAL_ENTRIES_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  excerpt: string | null
  publishedAt: string | null
  hasBody: false | true
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  author: {
    _id: string
    name: string | null
    photo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
    website: string | null
    socials: Array<{
      platform:
        "github" | "instagram" | "linkedin" | "twitter" | "youtube" | null
      url: string | null
    }> | null
  } | null
  tags: Array<{
    _id: string
    name: string | null
    slug: Slug | null
  }> | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: JOURNAL_ENTRY_COUNT_QUERY
// Query: count(*[_type == "journalEntry" &&   (!defined($tagSlug) || $tagSlug in tags[]->slug.current) &&  (!defined($search) || title match $search + "*" || excerpt match $search + "*")])
export type JOURNAL_ENTRY_COUNT_QUERY_RESULT = number

// Source: ../../packages/sanity/src/query.ts
// Variable: JOURNAL_ENTRY_BY_SLUG_QUERY
// Query: *[_type == "journalEntry" && slug.current == $slug][0] {      _id,  title,  slug,  excerpt,  publishedAt,  body,  coverImage {    asset->,    hotspot,    crop,    alt  },  ogImage {    asset->,    hotspot,    crop,    alt  },    author-> {    _id,    name,    photo {      asset->,      hotspot,      crop,      alt    },    website,    socials[] {      platform,      url    }  },  tags[]-> {    _id,    name,    slug  },  _updatedAt  }
export type JOURNAL_ENTRY_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: Slug | null
  excerpt: string | null
  publishedAt: string | null
  body: BlockContent | null
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  ogImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: string | null
  } | null
  author: {
    _id: string
    name: string | null
    photo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: string | null
    } | null
    website: string | null
    socials: Array<{
      platform:
        "github" | "instagram" | "linkedin" | "twitter" | "youtube" | null
      url: string | null
    }> | null
  } | null
  tags: Array<{
    _id: string
    name: string | null
    slug: Slug | null
  }> | null
  _updatedAt: string
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: JOURNAL_ENTRY_SLUGS_QUERY
// Query: *[_type == "journalEntry" && defined(slug.current)] | order(publishedAt desc) {    _id,    title,    slug,    publishedAt  }
export type JOURNAL_ENTRY_SLUGS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  publishedAt: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: LATEST_JOURNAL_ENTRIES_QUERY
// Query: *[_type == "journalEntry"] | order(publishedAt desc) [0...5] {    _id,    title,    slug,    publishedAt  }
export type LATEST_JOURNAL_ENTRIES_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  publishedAt: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: TAGS_QUERY
// Query: *[_type == "tag"] | order(name asc) {    _id,    name,    slug,    description  }
export type TAGS_QUERY_RESULT = Array<{
  _id: string
  name: string | null
  slug: Slug | null
  description: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: TAG_BY_SLUG_QUERY
// Query: *[_type == "tag" && slug.current == $slug][0] {    _id,    name,    slug,    description  }
export type TAG_BY_SLUG_QUERY_RESULT = {
  _id: string
  name: string | null
  slug: Slug | null
  description: string | null
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: WRITING_BY_TAG_QUERY
// Query: *[(_type == "post" || _type == "journalEntry") && $tagSlug in tags[]->slug.current] | order(publishedAt desc) [$start...$end] {    "kind": _type,      _id,  title,  slug,  excerpt,  publishedAt,  "hasBody": defined(body),  coverImage {    asset->,    hotspot,    crop,    alt  },    author-> {    _id,    name,    photo {      asset->,      hotspot,      crop,      alt    },    website,    socials[] {      platform,      url    }  },  tags[]-> {    _id,    name,    slug  }  }
export type WRITING_BY_TAG_QUERY_RESULT = Array<
  | {
      kind: "journalEntry"
      _id: string
      title: string | null
      slug: Slug | null
      excerpt: string | null
      publishedAt: string | null
      hasBody: false | true
      coverImage: {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash?: string
          extension?: string
          mimeType?: string
          size?: number
          assetId?: string
          uploadId?: string
          path?: string
          url?: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
        alt: string | null
      } | null
      author: {
        _id: string
        name: string | null
        photo: {
          asset: {
            _id: string
            _type: "sanity.imageAsset"
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          hotspot: SanityImageHotspot | null
          crop: SanityImageCrop | null
          alt: string | null
        } | null
        website: string | null
        socials: Array<{
          platform:
            "github" | "instagram" | "linkedin" | "twitter" | "youtube" | null
          url: string | null
        }> | null
      } | null
      tags: Array<{
        _id: string
        name: string | null
        slug: Slug | null
      }> | null
    }
  | {
      kind: "post"
      _id: string
      title: string | null
      slug: Slug | null
      excerpt: string | null
      publishedAt: string | null
      hasBody: false | true
      coverImage: {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash?: string
          extension?: string
          mimeType?: string
          size?: number
          assetId?: string
          uploadId?: string
          path?: string
          url?: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
        alt: string | null
      } | null
      author: {
        _id: string
        name: string | null
        photo: {
          asset: {
            _id: string
            _type: "sanity.imageAsset"
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          hotspot: SanityImageHotspot | null
          crop: SanityImageCrop | null
          alt: string | null
        } | null
        website: string | null
        socials: Array<{
          platform:
            "github" | "instagram" | "linkedin" | "twitter" | "youtube" | null
          url: string | null
        }> | null
      } | null
      tags: Array<{
        _id: string
        name: string | null
        slug: Slug | null
      }> | null
    }
>

// Source: ../../packages/sanity/src/query.ts
// Variable: WRITING_COUNT_BY_TAG_QUERY
// Query: count(*[(_type == "post" || _type == "journalEntry") && $tagSlug in tags[]->slug.current])
export type WRITING_COUNT_BY_TAG_QUERY_RESULT = number

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "siteConfig"][0] {\n    _id,\n    title,\n    description,\n    footerBlurb,\n    ogImage {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    twitterImage {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    logo {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    heroName,\n    heroRoles,\n    heroImage {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    aboutHeadingLead,\n    aboutHeadingHighlight,\n    aboutBody,\n    aboutHighlights[] {\n      title,\n      description\n    },\n    aboutImage {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    testimonialsHeadingLead,\n    testimonialsHeadingHighlight,\n    testimonialsIntro,\n    phoneNumbers[] {\n      number,\n      label\n    },\n    emails[] {\n      email,\n      label\n    },\n    contactNotificationEmail,\n    address {\n      street,\n      city,\n      state,\n      postalCode,\n      country\n    },\n    socialMedia[] {\n      platform,\n      url,\n      label\n    },\n    resumePdf {\n      asset->\n    },\n    rickrollAudio {\n      asset->\n    }\n  }\n': SITE_CONFIG_QUERY_RESULT
    '\n  *[_type == "siteConfig"][0] {\n    aboutPageHeadingLead,\n    aboutPageHeadingHighlight,\n    aboutPageIntro,\n    aboutPageStoryHeadingLead,\n    aboutPageStoryHeadingHighlight,\n    aboutPageStoryHeadingTrail,\n    aboutPageStory,\n    aboutPageValuesHeading,\n    aboutPageValuesIntro,\n    aboutPagePortrait {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    }\n  }\n': ABOUT_PAGE_QUERY_RESULT
    '\n  *[_type == "siteConfig"][0].footerLegalLinks[]-> {\n    _id,\n    title,\n    slug,\n    description,\n    _updatedAt\n  }\n': FOOTER_LEGAL_LINKS_QUERY_RESULT
    '\n  *[_type == "faqs"][0] {\n    ...,\n    faqItems[]{ ... }\n  }\n': FAQS_QUERY_RESULT
    '\n  *[_type == "legal"] | order(_updatedAt desc) {\n    _id,\n    title,\n    slug,\n    description,\n    _createdAt,\n    _updatedAt\n  }\n': LEGAL_DOCUMENTS_QUERY_RESULT
    '\n  *[_type == "legal" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    description,\n    content,\n    _createdAt,\n    _updatedAt\n  }\n': LEGAL_DOCUMENT_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "skill" && featured == true] | order(orderRank asc, name asc) {\n    _id,\n    name,\n    icon {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    category\n  }\n': FEATURED_SKILLS_QUERY_RESULT
    '\n  *[_type == "skill"] | order(category asc, orderRank asc, name asc) {\n    _id,\n    name,\n    icon {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    category\n  }\n': SKILLS_QUERY_RESULT
    '\n  *[_type == "service"] | order(orderRank asc) {\n    _id,\n    name,\n    description,\n    icon,\n    illustration {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    }\n  }\n': SERVICES_QUERY_RESULT
    '\n  *[_type == "service" && _id in $ids] {\n    _id,\n    name\n  }\n': SERVICES_BY_IDS_QUERY_RESULT
    '\n  *[_type == "value"] | order(orderRank asc) {\n    _id,\n    title,\n    description,\n    illustration {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    }\n  }\n': VALUES_QUERY_RESULT
    '\n  *[_type == "experience" && kind == "work" && featured == true] | order(orderRank asc) {\n    _id,\n    role,\n    organization-> {\n      _id,\n      name,\n      website,\n      logo {\n        asset->,\n        hotspot,\n        crop,\n        alt\n      }\n    },\n    employmentType,\n    startDate,\n    endDate,\n    isCurrent,\n    summary\n  }\n': FEATURED_EXPERIENCES_QUERY_RESULT
    '\n  *[_type == "experience" && kind in ["work", "community"]] | order(orderRank asc) {\n    _id,\n    role,\n    kind,\n    organization-> {\n      _id,\n      name,\n      website,\n      description,\n      logo {\n        asset->,\n        hotspot,\n        crop,\n        alt\n      }\n    },\n    employmentType,\n    workMode,\n    location,\n    startDate,\n    endDate,\n    isCurrent,\n    summary,\n    highlights,\n    skills[]-> {\n      _id,\n      name\n    },\n    links[] {\n      label,\n      url,\n      type\n    }\n  }\n': EXPERIENCES_QUERY_RESULT
    '\n  *[_type == "experience" && kind == "education"] | order(orderRank asc) {\n    _id,\n    role,\n    organization-> {\n      _id,\n      name,\n      website,\n      logo {\n        asset->,\n        hotspot,\n        crop,\n        alt\n      }\n    },\n    location,\n    startDate,\n    endDate,\n    isCurrent,\n    summary,\n    highlights,\n    credential,\n    links[] {\n      label,\n      url,\n      type\n    }\n  }\n': EDUCATION_QUERY_RESULT
    '\n  *[_type == "certification" && archived != true] | order(orderRank asc) {\n    _id,\n    title,\n    organization-> {\n      _id,\n      name,\n      website,\n      logo {\n        asset->,\n        hotspot,\n        crop,\n        alt\n      }\n    },\n    issuedAt,\n    credentialId,\n    verifyUrl\n  }\n': CERTIFICATIONS_QUERY_RESULT
    '\n  *[_type == "certification" && archived == true] | order(orderRank asc) {\n    _id,\n    title,\n    organization-> {\n      _id,\n      name,\n      website,\n      logo {\n        asset->,\n        hotspot,\n        crop,\n        alt\n      }\n    },\n    issuedAt,\n    credentialId,\n    verifyUrl\n  }\n': ARCHIVED_CERTIFICATIONS_QUERY_RESULT
    '\n  *[_type == "publication"] | order(orderRank asc) {\n    _id,\n    title,\n    venue,\n    publishedAt,\n    authors,\n    doi,\n    url,\n    abstract\n  }\n': PUBLICATIONS_QUERY_RESULT
    '\n  *[_type == "project" && featured == true && archived != true] | order(orderRank asc) [0...6] {\n    _id,\n    title,\n    slug,\n    kind,\n    status,\n    tagline,\n    summary,\n    "hasBody": defined(body),\n    icon {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    coverImage {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    organization-> {\n      _id,\n      name,\n      website\n    },\n    skills[]-> {\n      _id,\n      name\n    },\n    links[] {\n      label,\n      url,\n      type\n    },\n    githubRepo,\n    startDate,\n    completedAt\n  }\n': FEATURED_PROJECTS_QUERY_RESULT
    '\n  *[_type == "project"] | order(orderRank asc) {\n    _id,\n    title,\n    slug,\n    kind,\n    status,\n    tagline,\n    summary,\n    "hasBody": defined(body),\n    archived,\n    featured,\n    icon {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    coverImage {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    organization-> {\n      _id,\n      name,\n      website\n    },\n    relatedExperience-> {\n      _id,\n      role,\n      employmentType\n    },\n    skills[]-> {\n      _id,\n      name\n    },\n    links[] {\n      label,\n      url,\n      type\n    },\n    githubRepo,\n    startDate,\n    completedAt\n  }\n': PROJECTS_QUERY_RESULT
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    kind,\n    status,\n    tagline,\n    summary,\n    body,\n    archived,\n    icon {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    coverImage {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    gallery[] {\n      asset->,\n      hotspot,\n      crop,\n      alt,\n      caption\n    },\n    organization-> {\n      _id,\n      name,\n      website,\n      description,\n      logo {\n        asset->,\n        hotspot,\n        crop,\n        alt\n      }\n    },\n    relatedExperience-> {\n      _id,\n      role,\n      employmentType,\n      startDate,\n      endDate,\n      isCurrent,\n      organization-> {\n        _id,\n        name\n      }\n    },\n    skills[]-> {\n      _id,\n      name,\n      category\n    },\n    links[] {\n      label,\n      url,\n      type\n    },\n    githubRepo,\n    startDate,\n    completedAt,\n    _updatedAt\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "project" && defined(slug.current)] | order(orderRank asc) {\n    _id,\n    title,\n    slug,\n    coverImage {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    }\n  }\n': PROJECT_SLUGS_QUERY_RESULT
    '\n  *[_type == "testimonial"] | order(orderRank asc) {\n    \n  _id,\n  quote,\n  context,\n  givenAt,\n  author-> {\n    _id,\n    name,\n    position,\n    website,\n    organizationName,\n    photo {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    organization-> {\n      _id,\n      name,\n      website,\n      logo {\n        asset->,\n        hotspot,\n        crop,\n        alt\n      }\n    }\n  }\n\n  }\n': TESTIMONIALS_QUERY_RESULT
    '\n  *[_type == "testimonial" && featured == true] | order(orderRank asc) {\n    \n  _id,\n  quote,\n  context,\n  givenAt,\n  author-> {\n    _id,\n    name,\n    position,\n    website,\n    organizationName,\n    photo {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    organization-> {\n      _id,\n      name,\n      website,\n      logo {\n        asset->,\n        hotspot,\n        crop,\n        alt\n      }\n    }\n  }\n\n  }\n': FEATURED_TESTIMONIALS_QUERY_RESULT
    '\n  *[_type == "post" && \n  (!defined($tagSlug) || $tagSlug in tags[]->slug.current) &&\n  (!defined($search) || title match $search + "*" || excerpt match $search + "*")\n] | order(publishedAt desc) [$start...$end] {\n    \n  _id,\n  title,\n  slug,\n  excerpt,\n  publishedAt,\n  "hasBody": defined(body),\n  coverImage {\n    asset->,\n    hotspot,\n    crop,\n    alt\n  },\n  \n  author-> {\n    _id,\n    name,\n    photo {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    website,\n    socials[] {\n      platform,\n      url\n    }\n  }\n,\n  tags[]-> {\n    _id,\n    name,\n    slug\n  }\n\n  }\n': POSTS_QUERY_RESULT
    '\n  count(*[_type == "post" && \n  (!defined($tagSlug) || $tagSlug in tags[]->slug.current) &&\n  (!defined($search) || title match $search + "*" || excerpt match $search + "*")\n])\n': POST_COUNT_QUERY_RESULT
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  slug,\n  excerpt,\n  publishedAt,\n  body,\n  coverImage {\n    asset->,\n    hotspot,\n    crop,\n    alt\n  },\n  ogImage {\n    asset->,\n    hotspot,\n    crop,\n    alt\n  },\n  \n  author-> {\n    _id,\n    name,\n    photo {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    website,\n    socials[] {\n      platform,\n      url\n    }\n  }\n,\n  tags[]-> {\n    _id,\n    name,\n    slug\n  },\n  _updatedAt\n\n  }\n': POST_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    publishedAt\n  }\n': POST_SLUGS_QUERY_RESULT
    '\n  *[_type == "post"] | order(publishedAt desc) [0...5] {\n    _id,\n    title,\n    slug,\n    publishedAt\n  }\n': LATEST_POSTS_QUERY_RESULT
    '\n  *[_type == "journalEntry" && \n  (!defined($tagSlug) || $tagSlug in tags[]->slug.current) &&\n  (!defined($search) || title match $search + "*" || excerpt match $search + "*")\n] | order(publishedAt desc) [$start...$end] {\n    \n  _id,\n  title,\n  slug,\n  excerpt,\n  publishedAt,\n  "hasBody": defined(body),\n  coverImage {\n    asset->,\n    hotspot,\n    crop,\n    alt\n  },\n  \n  author-> {\n    _id,\n    name,\n    photo {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    website,\n    socials[] {\n      platform,\n      url\n    }\n  }\n,\n  tags[]-> {\n    _id,\n    name,\n    slug\n  }\n\n  }\n': JOURNAL_ENTRIES_QUERY_RESULT
    '\n  count(*[_type == "journalEntry" && \n  (!defined($tagSlug) || $tagSlug in tags[]->slug.current) &&\n  (!defined($search) || title match $search + "*" || excerpt match $search + "*")\n])\n': JOURNAL_ENTRY_COUNT_QUERY_RESULT
    '\n  *[_type == "journalEntry" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  slug,\n  excerpt,\n  publishedAt,\n  body,\n  coverImage {\n    asset->,\n    hotspot,\n    crop,\n    alt\n  },\n  ogImage {\n    asset->,\n    hotspot,\n    crop,\n    alt\n  },\n  \n  author-> {\n    _id,\n    name,\n    photo {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    website,\n    socials[] {\n      platform,\n      url\n    }\n  }\n,\n  tags[]-> {\n    _id,\n    name,\n    slug\n  },\n  _updatedAt\n\n  }\n': JOURNAL_ENTRY_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "journalEntry" && defined(slug.current)] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    publishedAt\n  }\n': JOURNAL_ENTRY_SLUGS_QUERY_RESULT
    '\n  *[_type == "journalEntry"] | order(publishedAt desc) [0...5] {\n    _id,\n    title,\n    slug,\n    publishedAt\n  }\n': LATEST_JOURNAL_ENTRIES_QUERY_RESULT
    '\n  *[_type == "tag"] | order(name asc) {\n    _id,\n    name,\n    slug,\n    description\n  }\n': TAGS_QUERY_RESULT
    '\n  *[_type == "tag" && slug.current == $slug][0] {\n    _id,\n    name,\n    slug,\n    description\n  }\n': TAG_BY_SLUG_QUERY_RESULT
    '\n  *[(_type == "post" || _type == "journalEntry") && $tagSlug in tags[]->slug.current] | order(publishedAt desc) [$start...$end] {\n    "kind": _type,\n    \n  _id,\n  title,\n  slug,\n  excerpt,\n  publishedAt,\n  "hasBody": defined(body),\n  coverImage {\n    asset->,\n    hotspot,\n    crop,\n    alt\n  },\n  \n  author-> {\n    _id,\n    name,\n    photo {\n      asset->,\n      hotspot,\n      crop,\n      alt\n    },\n    website,\n    socials[] {\n      platform,\n      url\n    }\n  }\n,\n  tags[]-> {\n    _id,\n    name,\n    slug\n  }\n\n  }\n': WRITING_BY_TAG_QUERY_RESULT
    '\n  count(*[(_type == "post" || _type == "journalEntry") && $tagSlug in tags[]->slug.current])\n': WRITING_COUNT_BY_TAG_QUERY_RESULT
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
