/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type Faqs = {
  _id: string
  _type: "faqs"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  faqItems?: Array<{
    question?: string
    answer?: string
    _key: string
  }>
}

export type Legal = {
  _id: string
  _type: "legal"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  content?: BlockContent
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote"
      listItem?: "bullet"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: "image"
      _key: string
    }
>

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type LegalReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "legal"
}

export type SiteConfig = {
  _id: string
  _type: "siteConfig"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  twitterImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  phoneNumbers?: Array<{
    number?: string
    label?: string
    _key: string
  }>
  emails?: Array<{
    email?: string
    label?: string
    _key: string
  }>
  address?: {
    street?: string
    city?: string
    state?: string
    postalCode?: string
    country?: string
  }
  socialMedia?: Array<{
    platform?:
      "twitter" | "youtube" | "instagram" | "facebook" | "whatsapp" | "linkedin"
    url?: string
    label?: string
    _key: string
  }>
  footerLegalLinks?: Array<
    {
      _key: string
    } & LegalReference
  >
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Faqs
  | Legal
  | SanityImageAssetReference
  | BlockContent
  | Slug
  | LegalReference
  | SiteConfig
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../../packages/sanity/src/query.ts
// Variable: SITE_CONFIG_QUERY
// Query: *[_type == "siteConfig"][0] {    _id,    title,    description,    ogImage {      asset->,      alt    },    twitterImage {      asset->,      alt    },    phoneNumbers[] {      number,      label    },    emails[] {      email,      label    },    address {      street,      city,      state,      postalCode,      country    },    socialMedia[] {      platform,      url,      label    }  }
export type SITE_CONFIG_QUERY_RESULT = {
  _id: string
  title: string | null
  description: string | null
  ogImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  twitterImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  phoneNumbers: Array<{
    number: string | null
    label: string | null
  }> | null
  emails: Array<{
    email: string | null
    label: string | null
  }> | null
  address: {
    street: string | null
    city: string | null
    state: string | null
    postalCode: string | null
    country: string | null
  } | null
  socialMedia: Array<{
    platform:
      | "facebook"
      | "instagram"
      | "linkedin"
      | "twitter"
      | "whatsapp"
      | "youtube"
      | null
    url: string | null
    label: string | null
  }> | null
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: FOOTER_LEGAL_LINKS_QUERY
// Query: *[_type == "siteConfig"][0].footerLegalLinks[]-> {    _id,    title,    slug,    description,    _updatedAt  }
export type FOOTER_LEGAL_LINKS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  _updatedAt: string
}> | null

// Source: ../../packages/sanity/src/query.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faqs"][0] {    ...,    faqItems[]{ ... }  }
export type FAQS_QUERY_RESULT = {
  _id: string
  _type: "faqs"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  faqItems: Array<{
    question?: string
    answer?: string
    _key: string
  }> | null
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: LEGAL_DOCUMENTS_QUERY
// Query: *[_type == "legal"] | order(_updatedAt desc) {    _id,    title,    slug,    description,    _createdAt,    _updatedAt  }
export type LEGAL_DOCUMENTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  _createdAt: string
  _updatedAt: string
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: LEGAL_DOCUMENT_BY_SLUG_QUERY
// Query: *[_type == "legal" && slug.current == $slug][0] {    _id,    title,    slug,    description,    content,    _createdAt,    _updatedAt  }
export type LEGAL_DOCUMENT_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  content: BlockContent | null
  _createdAt: string
  _updatedAt: string
} | null

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "siteConfig"][0] {\n    _id,\n    title,\n    description,\n    ogImage {\n      asset->,\n      alt\n    },\n    twitterImage {\n      asset->,\n      alt\n    },\n    phoneNumbers[] {\n      number,\n      label\n    },\n    emails[] {\n      email,\n      label\n    },\n    address {\n      street,\n      city,\n      state,\n      postalCode,\n      country\n    },\n    socialMedia[] {\n      platform,\n      url,\n      label\n    }\n  }\n': SITE_CONFIG_QUERY_RESULT
    '\n  *[_type == "siteConfig"][0].footerLegalLinks[]-> {\n    _id,\n    title,\n    slug,\n    description,\n    _updatedAt\n  }\n': FOOTER_LEGAL_LINKS_QUERY_RESULT
    '\n  *[_type == "faqs"][0] {\n    ...,\n    faqItems[]{ ... }\n  }\n': FAQS_QUERY_RESULT
    '\n  *[_type == "legal"] | order(_updatedAt desc) {\n    _id,\n    title,\n    slug,\n    description,\n    _createdAt,\n    _updatedAt\n  }\n': LEGAL_DOCUMENTS_QUERY_RESULT
    '\n  *[_type == "legal" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    description,\n    content,\n    _createdAt,\n    _updatedAt\n  }\n': LEGAL_DOCUMENT_BY_SLUG_QUERY_RESULT
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
