/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type OrganizationReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "organization"
}

export type ExperienceReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "experience"
}

export type SkillReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "skill"
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type Project = {
  _id: string
  _type: "project"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  kind?: "professional" | "freelance" | "personal" | "open-source" | "research"
  status?: "live" | "in-development" | "unlaunched" | "archived"
  tagline?: string
  summary?: string
  body?: BlockContent
  organization?: OrganizationReference
  relatedExperience?: ExperienceReference
  skills?: Array<
    {
      _key: string
    } & SkillReference
  >
  icon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  gallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: "image"
    _key: string
  }>
  links?: Array<{
    label?: string
    url?: string
    type?: "live-site" | "repo" | "case-study" | "video" | "paper"
    _key: string
  }>
  githubRepo?: string
  startDate?: string
  completedAt?: string
  featured?: boolean
  archived?: boolean
  orderRank?: string
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote"
      listItem?: "bullet"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: "image"
      _key: string
    }
>

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type Publication = {
  _id: string
  _type: "publication"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  venue?: string
  publishedAt?: string
  authors?: Array<string>
  doi?: string
  url?: string
  abstract?: string
  orderRank?: string
}

export type Experience = {
  _id: string
  _type: "experience"
  _createdAt: string
  _updatedAt: string
  _rev: string
  role?: string
  organization?: OrganizationReference
  kind?: "work" | "community" | "education"
  employmentType?:
    | "full-time"
    | "part-time"
    | "internship"
    | "contract"
    | "freelance"
    | "volunteer"
  workMode?: "on-site" | "remote" | "hybrid"
  location?: string
  startDate?: string
  endDate?: string
  isCurrent?: boolean
  summary?: string
  highlights?: Array<string>
  skills?: Array<
    {
      _key: string
    } & SkillReference
  >
  credential?: string
  links?: Array<{
    label?: string
    url?: string
    type?:
      "live-site" | "repo" | "certificate" | "letter" | "patent" | "publication"
    _key: string
  }>
  featured?: boolean
  orderRank?: string
}

export type Organization = {
  _id: string
  _type: "organization"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  website?: string
  description?: string
  orderRank?: string
}

export type Service = {
  _id: string
  _type: "service"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  description?: string
  illustration?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  orderRank?: string
}

export type Skill = {
  _id: string
  _type: "skill"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  icon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  category?:
    | "languages"
    | "frontend-mobile"
    | "backend"
    | "testing"
    | "payments-security"
    | "cms"
    | "cloud-infrastructure"
    | "auth-security"
    | "ai-ml"
    | "messaging-integrations"
    | "devops-tooling"
    | "databases"
    | "collaboration"
    | "other"
  featured?: boolean
  orderRank?: string
}

export type Faqs = {
  _id: string
  _type: "faqs"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  faqItems?: Array<{
    question?: string
    answer?: string
    _key: string
  }>
}

export type Legal = {
  _id: string
  _type: "legal"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  content?: BlockContent
}

export type SanityFileAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset"
}

export type LegalReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "legal"
}

export type SiteConfig = {
  _id: string
  _type: "siteConfig"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  twitterImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  heroName?: string
  heroRoles?: Array<string>
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  aboutHeadingLead?: string
  aboutHeadingHighlight?: string
  aboutBody?: string
  aboutHighlights?: Array<{
    title?: string
    description?: string
    _key: string
  }>
  aboutImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  phoneNumbers?: Array<{
    number?: string
    label?: string
    _key: string
  }>
  emails?: Array<{
    email?: string
    label?: string
    _key: string
  }>
  address?: {
    street?: string
    city?: string
    state?: string
    postalCode?: string
    country?: string
  }
  socialMedia?: Array<{
    platform?:
      "twitter" | "youtube" | "instagram" | "facebook" | "whatsapp" | "linkedin"
    url?: string
    label?: string
    _key: string
  }>
  resumePdf?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: "file"
  }
  footerLegalLinks?: Array<
    {
      _key: string
    } & LegalReference
  >
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | OrganizationReference
  | ExperienceReference
  | SkillReference
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | BlockContent
  | Slug
  | Publication
  | Experience
  | Organization
  | Service
  | Skill
  | Faqs
  | Legal
  | SanityFileAssetReference
  | LegalReference
  | SiteConfig
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../../packages/sanity/src/query.ts
// Variable: SITE_CONFIG_QUERY
// Query: *[_type == "siteConfig"][0] {    _id,    title,    description,    ogImage {      asset->,      alt    },    twitterImage {      asset->,      alt    },    logo {      asset->,      alt    },    heroName,    heroRoles,    heroImage {      asset->,      alt    },    aboutHeadingLead,    aboutHeadingHighlight,    aboutBody,    aboutHighlights[] {      title,      description    },    aboutImage {      asset->,      alt    },    phoneNumbers[] {      number,      label    },    emails[] {      email,      label    },    address {      street,      city,      state,      postalCode,      country    },    socialMedia[] {      platform,      url,      label    },    resumePdf {      asset->    }  }
export type SITE_CONFIG_QUERY_RESULT = {
  _id: string
  title: string | null
  description: string | null
  ogImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  twitterImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  logo: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  heroName: string | null
  heroRoles: Array<string> | null
  heroImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  aboutHeadingLead: string | null
  aboutHeadingHighlight: string | null
  aboutBody: string | null
  aboutHighlights: Array<{
    title: string | null
    description: string | null
  }> | null
  aboutImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  phoneNumbers: Array<{
    number: string | null
    label: string | null
  }> | null
  emails: Array<{
    email: string | null
    label: string | null
  }> | null
  address: {
    street: string | null
    city: string | null
    state: string | null
    postalCode: string | null
    country: string | null
  } | null
  socialMedia: Array<{
    platform:
      | "facebook"
      | "instagram"
      | "linkedin"
      | "twitter"
      | "whatsapp"
      | "youtube"
      | null
    url: string | null
    label: string | null
  }> | null
  resumePdf: {
    asset: {
      _id: string
      _type: "sanity.fileAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      source?: SanityAssetSourceData
    } | null
  } | null
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: FOOTER_LEGAL_LINKS_QUERY
// Query: *[_type == "siteConfig"][0].footerLegalLinks[]-> {    _id,    title,    slug,    description,    _updatedAt  }
export type FOOTER_LEGAL_LINKS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  _updatedAt: string
}> | null

// Source: ../../packages/sanity/src/query.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faqs"][0] {    ...,    faqItems[]{ ... }  }
export type FAQS_QUERY_RESULT = {
  _id: string
  _type: "faqs"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  faqItems: Array<{
    question?: string
    answer?: string
    _key: string
  }> | null
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: LEGAL_DOCUMENTS_QUERY
// Query: *[_type == "legal"] | order(_updatedAt desc) {    _id,    title,    slug,    description,    _createdAt,    _updatedAt  }
export type LEGAL_DOCUMENTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  _createdAt: string
  _updatedAt: string
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: LEGAL_DOCUMENT_BY_SLUG_QUERY
// Query: *[_type == "legal" && slug.current == $slug][0] {    _id,    title,    slug,    description,    content,    _createdAt,    _updatedAt  }
export type LEGAL_DOCUMENT_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  content: BlockContent | null
  _createdAt: string
  _updatedAt: string
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: FEATURED_SKILLS_QUERY
// Query: *[_type == "skill" && featured == true] | order(orderRank asc, name asc) {    _id,    name,    icon {      asset->,      alt    },    category  }
export type FEATURED_SKILLS_QUERY_RESULT = Array<{
  _id: string
  name: string | null
  icon: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  category:
    | "ai-ml"
    | "auth-security"
    | "backend"
    | "cloud-infrastructure"
    | "cms"
    | "collaboration"
    | "databases"
    | "devops-tooling"
    | "frontend-mobile"
    | "languages"
    | "messaging-integrations"
    | "other"
    | "payments-security"
    | "testing"
    | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: SKILLS_QUERY
// Query: *[_type == "skill"] | order(category asc, orderRank asc, name asc) {    _id,    name,    icon {      asset->,      alt    },    category  }
export type SKILLS_QUERY_RESULT = Array<{
  _id: string
  name: string | null
  icon: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  category:
    | "ai-ml"
    | "auth-security"
    | "backend"
    | "cloud-infrastructure"
    | "cms"
    | "collaboration"
    | "databases"
    | "devops-tooling"
    | "frontend-mobile"
    | "languages"
    | "messaging-integrations"
    | "other"
    | "payments-security"
    | "testing"
    | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(orderRank asc) {    _id,    name,    description,    illustration {      asset->,      alt    }  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string
  name: string | null
  description: string | null
  illustration: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: FEATURED_EXPERIENCES_QUERY
// Query: *[_type == "experience" && kind == "work" && featured == true] | order(orderRank asc) {    _id,    role,    organization-> {      _id,      name,      website,      logo {        asset->,        alt      }    },    employmentType,    startDate,    endDate,    isCurrent,    summary  }
export type FEATURED_EXPERIENCES_QUERY_RESULT = Array<{
  _id: string
  role: string | null
  organization: {
    _id: string
    name: string | null
    website: string | null
    logo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      alt: string | null
    } | null
  } | null
  employmentType:
    | "contract"
    | "freelance"
    | "full-time"
    | "internship"
    | "part-time"
    | "volunteer"
    | null
  startDate: string | null
  endDate: string | null
  isCurrent: boolean | null
  summary: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: EXPERIENCES_QUERY
// Query: *[_type == "experience" && kind in ["work", "community"]] | order(orderRank asc) {    _id,    role,    kind,    organization-> {      _id,      name,      website,      description,      logo {        asset->,        alt      }    },    employmentType,    workMode,    location,    startDate,    endDate,    isCurrent,    summary,    highlights,    skills[]-> {      _id,      name    },    links[] {      label,      url,      type    }  }
export type EXPERIENCES_QUERY_RESULT = Array<{
  _id: string
  role: string | null
  kind: "community" | "education" | "work" | null
  organization: {
    _id: string
    name: string | null
    website: string | null
    description: string | null
    logo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      alt: string | null
    } | null
  } | null
  employmentType:
    | "contract"
    | "freelance"
    | "full-time"
    | "internship"
    | "part-time"
    | "volunteer"
    | null
  workMode: "hybrid" | "on-site" | "remote" | null
  location: string | null
  startDate: string | null
  endDate: string | null
  isCurrent: boolean | null
  summary: string | null
  highlights: Array<string> | null
  skills: Array<{
    _id: string
    name: string | null
  }> | null
  links: Array<{
    label: string | null
    url: string | null
    type:
      | "certificate"
      | "letter"
      | "live-site"
      | "patent"
      | "publication"
      | "repo"
      | null
  }> | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: EDUCATION_QUERY
// Query: *[_type == "experience" && kind == "education"] | order(orderRank asc) {    _id,    role,    organization-> {      _id,      name,      website,      logo {        asset->,        alt      }    },    location,    startDate,    endDate,    isCurrent,    summary,    highlights,    credential,    links[] {      label,      url,      type    }  }
export type EDUCATION_QUERY_RESULT = Array<{
  _id: string
  role: string | null
  organization: {
    _id: string
    name: string | null
    website: string | null
    logo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      alt: string | null
    } | null
  } | null
  location: string | null
  startDate: string | null
  endDate: string | null
  isCurrent: boolean | null
  summary: string | null
  highlights: Array<string> | null
  credential: string | null
  links: Array<{
    label: string | null
    url: string | null
    type:
      | "certificate"
      | "letter"
      | "live-site"
      | "patent"
      | "publication"
      | "repo"
      | null
  }> | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: PUBLICATIONS_QUERY
// Query: *[_type == "publication"] | order(orderRank asc) {    _id,    title,    venue,    publishedAt,    authors,    doi,    url,    abstract  }
export type PUBLICATIONS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  venue: string | null
  publishedAt: string | null
  authors: Array<string> | null
  doi: string | null
  url: string | null
  abstract: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true && archived != true] | order(orderRank asc) {    _id,    title,    slug,    kind,    status,    tagline,    summary,    "hasBody": defined(body),    icon {      asset->,      alt    },    coverImage {      asset->,      alt    },    organization-> {      _id,      name,      website    },    skills[]-> {      _id,      name    },    links[] {      label,      url,      type    },    githubRepo,    startDate,    completedAt  }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  kind:
    | "freelance"
    | "open-source"
    | "personal"
    | "professional"
    | "research"
    | null
  status: "archived" | "in-development" | "live" | "unlaunched" | null
  tagline: string | null
  summary: string | null
  hasBody: false | true
  icon: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  organization: {
    _id: string
    name: string | null
    website: string | null
  } | null
  skills: Array<{
    _id: string
    name: string | null
  }> | null
  links: Array<{
    label: string | null
    url: string | null
    type: "case-study" | "live-site" | "paper" | "repo" | "video" | null
  }> | null
  githubRepo: string | null
  startDate: string | null
  completedAt: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(orderRank asc) {    _id,    title,    slug,    kind,    status,    tagline,    summary,    "hasBody": defined(body),    archived,    featured,    icon {      asset->,      alt    },    coverImage {      asset->,      alt    },    organization-> {      _id,      name,      website    },    relatedExperience-> {      _id,      role,      employmentType    },    skills[]-> {      _id,      name    },    links[] {      label,      url,      type    },    githubRepo,    startDate,    completedAt  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  kind:
    | "freelance"
    | "open-source"
    | "personal"
    | "professional"
    | "research"
    | null
  status: "archived" | "in-development" | "live" | "unlaunched" | null
  tagline: string | null
  summary: string | null
  hasBody: false | true
  archived: boolean | null
  featured: boolean | null
  icon: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  organization: {
    _id: string
    name: string | null
    website: string | null
  } | null
  relatedExperience: {
    _id: string
    role: string | null
    employmentType:
      | "contract"
      | "freelance"
      | "full-time"
      | "internship"
      | "part-time"
      | "volunteer"
      | null
  } | null
  skills: Array<{
    _id: string
    name: string | null
  }> | null
  links: Array<{
    label: string | null
    url: string | null
    type: "case-study" | "live-site" | "paper" | "repo" | "video" | null
  }> | null
  githubRepo: string | null
  startDate: string | null
  completedAt: string | null
}>

// Source: ../../packages/sanity/src/query.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    slug,    kind,    status,    tagline,    summary,    body,    archived,    icon {      asset->,      alt    },    coverImage {      asset->,      alt    },    gallery[] {      asset->,      alt,      caption    },    organization-> {      _id,      name,      website,      description,      logo {        asset->,        alt      }    },    relatedExperience-> {      _id,      role,      employmentType,      startDate,      endDate,      isCurrent,      organization-> {        _id,        name      }    },    skills[]-> {      _id,      name,      category    },    links[] {      label,      url,      type    },    githubRepo,    startDate,    completedAt,    _updatedAt  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: Slug | null
  kind:
    | "freelance"
    | "open-source"
    | "personal"
    | "professional"
    | "research"
    | null
  status: "archived" | "in-development" | "live" | "unlaunched" | null
  tagline: string | null
  summary: string | null
  body: BlockContent | null
  archived: boolean | null
  icon: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
  gallery: Array<{
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
    caption: string | null
  }> | null
  organization: {
    _id: string
    name: string | null
    website: string | null
    description: string | null
    logo: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      alt: string | null
    } | null
  } | null
  relatedExperience: {
    _id: string
    role: string | null
    employmentType:
      | "contract"
      | "freelance"
      | "full-time"
      | "internship"
      | "part-time"
      | "volunteer"
      | null
    startDate: string | null
    endDate: string | null
    isCurrent: boolean | null
    organization: {
      _id: string
      name: string | null
    } | null
  } | null
  skills: Array<{
    _id: string
    name: string | null
    category:
      | "ai-ml"
      | "auth-security"
      | "backend"
      | "cloud-infrastructure"
      | "cms"
      | "collaboration"
      | "databases"
      | "devops-tooling"
      | "frontend-mobile"
      | "languages"
      | "messaging-integrations"
      | "other"
      | "payments-security"
      | "testing"
      | null
  }> | null
  links: Array<{
    label: string | null
    url: string | null
    type: "case-study" | "live-site" | "paper" | "repo" | "video" | null
  }> | null
  githubRepo: string | null
  startDate: string | null
  completedAt: string | null
  _updatedAt: string
} | null

// Source: ../../packages/sanity/src/query.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(orderRank asc) {    _id,    title,    slug,    coverImage {      asset->,      alt    }  }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  coverImage: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
  } | null
}>

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "siteConfig"][0] {\n    _id,\n    title,\n    description,\n    ogImage {\n      asset->,\n      alt\n    },\n    twitterImage {\n      asset->,\n      alt\n    },\n    logo {\n      asset->,\n      alt\n    },\n    heroName,\n    heroRoles,\n    heroImage {\n      asset->,\n      alt\n    },\n    aboutHeadingLead,\n    aboutHeadingHighlight,\n    aboutBody,\n    aboutHighlights[] {\n      title,\n      description\n    },\n    aboutImage {\n      asset->,\n      alt\n    },\n    phoneNumbers[] {\n      number,\n      label\n    },\n    emails[] {\n      email,\n      label\n    },\n    address {\n      street,\n      city,\n      state,\n      postalCode,\n      country\n    },\n    socialMedia[] {\n      platform,\n      url,\n      label\n    },\n    resumePdf {\n      asset->\n    }\n  }\n': SITE_CONFIG_QUERY_RESULT
    '\n  *[_type == "siteConfig"][0].footerLegalLinks[]-> {\n    _id,\n    title,\n    slug,\n    description,\n    _updatedAt\n  }\n': FOOTER_LEGAL_LINKS_QUERY_RESULT
    '\n  *[_type == "faqs"][0] {\n    ...,\n    faqItems[]{ ... }\n  }\n': FAQS_QUERY_RESULT
    '\n  *[_type == "legal"] | order(_updatedAt desc) {\n    _id,\n    title,\n    slug,\n    description,\n    _createdAt,\n    _updatedAt\n  }\n': LEGAL_DOCUMENTS_QUERY_RESULT
    '\n  *[_type == "legal" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    description,\n    content,\n    _createdAt,\n    _updatedAt\n  }\n': LEGAL_DOCUMENT_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "skill" && featured == true] | order(orderRank asc, name asc) {\n    _id,\n    name,\n    icon {\n      asset->,\n      alt\n    },\n    category\n  }\n': FEATURED_SKILLS_QUERY_RESULT
    '\n  *[_type == "skill"] | order(category asc, orderRank asc, name asc) {\n    _id,\n    name,\n    icon {\n      asset->,\n      alt\n    },\n    category\n  }\n': SKILLS_QUERY_RESULT
    '\n  *[_type == "service"] | order(orderRank asc) {\n    _id,\n    name,\n    description,\n    illustration {\n      asset->,\n      alt\n    }\n  }\n': SERVICES_QUERY_RESULT
    '\n  *[_type == "experience" && kind == "work" && featured == true] | order(orderRank asc) {\n    _id,\n    role,\n    organization-> {\n      _id,\n      name,\n      website,\n      logo {\n        asset->,\n        alt\n      }\n    },\n    employmentType,\n    startDate,\n    endDate,\n    isCurrent,\n    summary\n  }\n': FEATURED_EXPERIENCES_QUERY_RESULT
    '\n  *[_type == "experience" && kind in ["work", "community"]] | order(orderRank asc) {\n    _id,\n    role,\n    kind,\n    organization-> {\n      _id,\n      name,\n      website,\n      description,\n      logo {\n        asset->,\n        alt\n      }\n    },\n    employmentType,\n    workMode,\n    location,\n    startDate,\n    endDate,\n    isCurrent,\n    summary,\n    highlights,\n    skills[]-> {\n      _id,\n      name\n    },\n    links[] {\n      label,\n      url,\n      type\n    }\n  }\n': EXPERIENCES_QUERY_RESULT
    '\n  *[_type == "experience" && kind == "education"] | order(orderRank asc) {\n    _id,\n    role,\n    organization-> {\n      _id,\n      name,\n      website,\n      logo {\n        asset->,\n        alt\n      }\n    },\n    location,\n    startDate,\n    endDate,\n    isCurrent,\n    summary,\n    highlights,\n    credential,\n    links[] {\n      label,\n      url,\n      type\n    }\n  }\n': EDUCATION_QUERY_RESULT
    '\n  *[_type == "publication"] | order(orderRank asc) {\n    _id,\n    title,\n    venue,\n    publishedAt,\n    authors,\n    doi,\n    url,\n    abstract\n  }\n': PUBLICATIONS_QUERY_RESULT
    '\n  *[_type == "project" && featured == true && archived != true] | order(orderRank asc) {\n    _id,\n    title,\n    slug,\n    kind,\n    status,\n    tagline,\n    summary,\n    "hasBody": defined(body),\n    icon {\n      asset->,\n      alt\n    },\n    coverImage {\n      asset->,\n      alt\n    },\n    organization-> {\n      _id,\n      name,\n      website\n    },\n    skills[]-> {\n      _id,\n      name\n    },\n    links[] {\n      label,\n      url,\n      type\n    },\n    githubRepo,\n    startDate,\n    completedAt\n  }\n': FEATURED_PROJECTS_QUERY_RESULT
    '\n  *[_type == "project"] | order(orderRank asc) {\n    _id,\n    title,\n    slug,\n    kind,\n    status,\n    tagline,\n    summary,\n    "hasBody": defined(body),\n    archived,\n    featured,\n    icon {\n      asset->,\n      alt\n    },\n    coverImage {\n      asset->,\n      alt\n    },\n    organization-> {\n      _id,\n      name,\n      website\n    },\n    relatedExperience-> {\n      _id,\n      role,\n      employmentType\n    },\n    skills[]-> {\n      _id,\n      name\n    },\n    links[] {\n      label,\n      url,\n      type\n    },\n    githubRepo,\n    startDate,\n    completedAt\n  }\n': PROJECTS_QUERY_RESULT
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    kind,\n    status,\n    tagline,\n    summary,\n    body,\n    archived,\n    icon {\n      asset->,\n      alt\n    },\n    coverImage {\n      asset->,\n      alt\n    },\n    gallery[] {\n      asset->,\n      alt,\n      caption\n    },\n    organization-> {\n      _id,\n      name,\n      website,\n      description,\n      logo {\n        asset->,\n        alt\n      }\n    },\n    relatedExperience-> {\n      _id,\n      role,\n      employmentType,\n      startDate,\n      endDate,\n      isCurrent,\n      organization-> {\n        _id,\n        name\n      }\n    },\n    skills[]-> {\n      _id,\n      name,\n      category\n    },\n    links[] {\n      label,\n      url,\n      type\n    },\n    githubRepo,\n    startDate,\n    completedAt,\n    _updatedAt\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "project" && defined(slug.current)] | order(orderRank asc) {\n    _id,\n    title,\n    slug,\n    coverImage {\n      asset->,\n      alt\n    }\n  }\n': PROJECT_SLUGS_QUERY_RESULT
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
